config/routes.rb
  resources :course_research_lines do
    concerns :active_scaffold
  end

  get "credits/show"

  resources :phase_durations do
    concerns :active_scaffold
  end

  resources :deferrals do
    concerns :active_scaffold
  end

  resources :deferral_types do
    concerns :active_scaffold
  end

  resources :accomplishments do
    concerns :active_scaffold
  end

  resources :phases do
    concerns :active_scaffold
  end

  resources :cities do
    concerns :active_scaffold
    get "autocomplete", on: :collection
  end

  resources :states do
    concerns :active_scaffold
    get "cities", on: :member
    get "autocomplete", on: :collection
  end

  resources :countries do
    concerns :active_scaffold
    get "states", on: :member
    get "autocomplete", on: :collection
  end

  resources :users do
    concerns :active_scaffold
    record_select_routes
  end

  resources :roles do
    concerns :active_scaffold
  end

  resources :user_roles do
    concerns :active_scaffold
    record_select_routes
  end

  

  resources :scholarship_durations do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
    end
  end

  resources :scholarships do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
    end
  end

  resources :advisements do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
    end
  end

  resources :affiliation do
    concerns :active_scaffold
    record_select_routes
  end

  resources :professors do
    concerns :active_scaffold
    record_select_routes
  end

  resources :scholarship_types do
    concerns :active_scaffold
  end

  resources :dismissals do
    concerns :active_scaffold
  end

  resources :dismissal_reasons do
    concerns :active_scaffold
  end

  resources :enrollments do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
      get "new_users"
      post "create_users"
    end
    member do
      get "academic_transcript_pdf"
      get "academic_transcript/:signature_type.pdf", to: "enrollments#override_signature_transcript_pdf", as: :override_signature_transcript_pdf
      get "grades_report_pdf"
      get "grades_report/:signature_type.pdf", to: "enrollments#override_signature_grades_report_pdf", as: :override_signature_grades_report_pdf
    end
  end

  resources :enrollment_statuses do
    concerns :active_scaffold
  end

  resources :students do
    concerns :active_scaffold
    record_select_routes
  end

  resources :majors do
    concerns :active_scaffold
    record_select_routes
  end

  resources :assertions do
    concerns :active_scaffold
  end

  resources :levels do
    concerns :active_scaffold
  end

  resources :institutions do
    concerns :active_scaffold
    record_select_routes
  end

  resources :sponsors do
    concerns :active_scaffold
  end

  resources :advisement_authorizations do
    concerns :active_scaffold
  end

  resources :student_majors do
    concerns :active_scaffold
    record_select_routes
  end

  resources :custom_variables do
    concerns :active_scaffold
  end

  resources :program_levels do
    concerns :active_scaffold
  end

  resources :thesis_defense_committee_participations do
    concerns :active_scaffold
    record_select_routes
  end

  resources :notification_logs do
    concerns :active_scaffold
  end

  resources :notifications do
    concerns :active_scaffold
    member do
      post "execute_now"
      get "simulate"
    end

    collection do
      get "notify"
    end
  end

  resources :queries do
    concerns :active_scaffold
    member do
      get "execute"
    end
  end

  resources :query_params do
    concerns :active_scaffold
  end

  resources :report_configurations do
    concerns :active_scaffold
    collection do
      put "preview"
      post "preview"
      patch "preview"
    end
    member do
      get "logo"
    end
  end


  resources :course_research_areas do
    concerns :active_scaffold
  end

  scope module: "admissions" do
    resources :admission_processes do
      concerns :active_scaffold
      member do
        get :short_pdf
        get :complete_pdf
        get :complete_xls

        get :phase_status
        post :consolidate_phase
        get :rankings
        post :calculate_ranking
      end
      collection do
        get :custom_report
        match :reset_report, via: [:get, :post]
        post :custom_report_generate
      end
      record_select_routes
    end

    resources :admission_applications do
      concerns :active_scaffold
      collection do
        get :configure_all
      end
      member do
        get :configuration
        put :undo_consolidation
        put :cancel
        get :map_student
        post :map_student_form
        post :map_student_form_create_update
      end
      record_select_routes
    end

    resources :form_templates do
      concerns :active_scaffold
      get :populate_field, on: :collection
      member do
        get :populate_field
        get :preview
        post :preview
        patch :preview
      end
      record_select_routes
    end

    resources :consolidation_templates do
      concerns :active_scaffold
    end

    resources :form_fields do
      concerns :active_scaffold
    end

    resources :consolidation_form_fields do
      concerns :active_scaffold
    end

    resources :filled_forms do
      concerns :active_scaffold
    end

    resources :filled_form_fields do
      concerns :active_scaffold
    end

    resources :filled_form_field_scholarities do
      concerns :active_scaffold
    end

    resources :letter_requests do
      concerns :active_scaffold
    end

    resources :admissions, only: [:index, :show] do
      post :find, on: :collection
      post :create, on: :member
      resources :apply, only: [:show, :new, :create, :edit, :update] do
        post :update, on: :member
      end
      resources :letters, only: [:show, :update]
    end

    resources :form_autocompletes, only: [] do
      get :city, on: :collection
      get :state, on: :collection
      get :country, on: :collection
      get :institution, on: :collection
      get :course, on: :collection
      get :form_field, on: :collection
    end

    resources :form_conditions do
      concerns :active_scaffold
    end

    resources :admission_committees do
      concerns :active_scaffold
      get :populate_authorized, on: :collection
      get :populate_professors, on: :collection
      get :populate_coordination, on: :collection
      get :populate_secretary, on: :collection
      member do
        get :populate_authorized
        get :populate_professors
        get :populate_coordination
        get :populate_secretary
      end
      record_select_routes
    end

    resources :admission_committee_members do
      concerns :active_scaffold
    end

    resources :admission_phases do
      concerns :active_scaffold
      record_select_routes
    end

    resources :admission_phase_committees do
      concerns :active_scaffold
    end

    resources :admission_process_phases do
      concerns :active_scaffold
    end

    resources :admission_phase_results do
      concerns :active_scaffold
    end

    resources :admission_phase_evaluations do
      concerns :active_scaffold
    end

    resources :admission_pendencies do
      concerns :active_scaffold
    end

    resources :ranking_machines do
      concerns :active_scaffold
      record_select_routes
    end

    resources :ranking_configs do
      concerns :active_scaffold
      record_select_routes
    end

    resources :ranking_columns do
      concerns :active_scaffold
    end

    resources :ranking_groups do
      concerns :active_scaffold
    end

    resources :ranking_processes do
      concerns :active_scaffold
    end

    resources :admission_process_rankings do
      concerns :active_scaffold
    end

    resources :admission_ranking_results do
      concerns :active_scaffold
    end

    resources :admission_report_configs do
      concerns :active_scaffold
      record_select_routes
    end

    resources :admission_report_groups do
      concerns :active_scaffold
    end

    resources :admission_report_columns do
      concerns :active_scaffold
    end
  end

  get "landing", action: :index, controller: "landing"
  get "files/:medium_hash", action: :download, controller: "files", as: :download
  get "admissions/files/:medium_hash", action: :download, controller: "files"
  get "enrollment/:id", to: "student_enrollment#show", as: :student_enrollment
  get "enrollment/:id/enroll/:year-:semester",
    to: "student_enrollment#enroll", as: :student_enroll
  post "enrollment/:id/enroll/:year-:semester",
    to: "student_enrollment#save_enroll", as: :save_student_enroll

  get "pendencies", to: "pendencies#index", as: :pendencies


  resources :enrollment_requests do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "help"
    end
  end
  resources :class_enrollment_requests do
    concerns :active_scaffold
    collection do
      get "help"
      get "show_effect"
      post "effect"
    end
    member do
      put "set_invalid"
      put "set_requested"
      put "set_valid"
      put "set_effected"
    end
  end
  resources :enrollment_request_comments, concerns: :active_scaffold
  resources :email_templates do
    concerns :active_scaffold
    collection do
      get "builtin"
    end
  end


  resources :email_templates do
    concerns :active_scaffold
    collection do
      get "builtin"
    end
  end

  resources :assertions do
    concerns :active_scaffold
    member do
      get "simulate"
      get "assertion_pdf"
      get "assertion_pdf/:signature_type.pdf", to: "assertions#override_signature_assertion_pdf",  as: :override_signature_assertion_pdf
    end
  end

  resources :reports do
    concerns :active_scaffold
    member do
      get :download
      put :invalidate

app/controllers/notifications_controller.rb
# Copyright (c) Universidade Federal Fluminense (UFF).
# This file is part of SAPOS. Please, consult the license terms in the LICENSE file.

# frozen_string_literal: true

class NotificationsController < ApplicationController
  include SharedPdfConcern

  authorize_resource
  skip_authorization_check only: [:notify]
  skip_before_action :authenticate_user!, only: :notify
  before_action :permit_query_params
  helper PdfHelper
  helper EnrollmentsPdfHelper

  def permit_query_params
    params[:query_params].permit! unless params[:query_params].nil?
  end

  active_scaffold :"notification" do |config|
    config.action_links.add(
      "simulate",
      label: "<i title='#{I18n.t("active_scaffold.notification.simulate")}'
                 class='fa fa-table'></i>".html_safe,
      page: true,
      inline: true,
      position: :after,
      type: :member
    )

    form_columns = [
      :title, :frequency, :notification_offset, :query_offset, :query,
      :individual, :has_grades_report_pdf_attachment, :template_type,
      :to_template, :subject_template, :body_template
    ]
    config.columns = form_columns
    config.update.columns = form_columns
    config.create.columns = [
      :title, :frequency, :notification_offset, :query_offset, :query,
      :individual, :has_grades_report_pdf_attachment,
      :to_template, :subject_template, :body_template
    ]
    config.show.columns = form_columns + [:next_execution]
    config.list.columns = [
      :title, :frequency, :notification_offset, :query_offset, :next_execution
    ]

    config.columns[:query].form_ui = :select
    config.columns[:frequency].form_ui = :select
    config.columns[:frequency].options = { options: Notification::FREQUENCIES }
    config.columns[:frequency].description = I18n.t(
      "active_scaffold.notification.frequency_description"
    )
    config.columns[:individual].description = I18n.t(
      "active_scaffold.notification.individual_description"
    )
    config.columns[:has_grades_report_pdf_attachment].description = I18n.t(
      "active_scaffold.notification.has_grades_report_pdf_attachment_description"
    )
    config.columns[:notification_offset].description = I18n.t(
      "active_scaffold.notification.notification_offset_description"
    )
    config.columns[:query_offset].description = I18n.t(
      "active_scaffold.notification.query_offset_description"
    )
    config.columns[:query].update_columns = [:query]
    config.columns[:template_type].form_ui = :select
    config.columns[:template_type].options = {
      options: Notification::TEMPLATE_TYPES,
    }
    #config.columns[:to_template].description = "Use {% emails Secretaria %} para todos emails de usuários da secretaria."


    config.create.label = :create_notification_label

    config.actions.exclude :deleted_records
  end

  def after_update_save(record)
    record.update_next_execution!
  end

  def execute_now
    process_action_link_action do |notification|
      result = notification.execute(override_params: get_query_params)
      Notifier.send_emails(prepare_attachments(result))
      self.successful = true

      flash[:info] = I18n.t("active_scaffold.notification.execute_now_success")
    end
  end

  def simulate
    @notification = Notification.find(params[:id])
    # Execute notification with current parameters
    args = @notification.prepare_params_and_derivations(get_query_params)
    result = @notification.execute(skip_update: true, override_params: args)
    @messages = result[:notifications]
    @query_sql = result[:query]

    # Allow user to simulate with different arguments
    # Analyzes derivations and builds new temporary parameters for missing ones
    # Also set simulation_value based on arguments
    @query_params = @notification.query.params
    existing_der = Set.new
    used_der = Set.new
    @query_params.each do |param|
      # Find derivations
      name = param.name
      existing_der << name if Notification::DERIVATION_DEFS.include? name
      derivation = Notification::DERIVED_PARAMS[name]
      used_der << derivation if derivation.present?
      # Set default value
      user_value = args[name.to_sym]
      param.simulation_value = user_value unless user_value.nil?
    end
    missing_derivations = used_der - existing_der
    missing_derivations.each do |param_name|
      param = @query_params.build(Notification::DERIVATION_DEFS[param_name])
      # Set default value
      user_value = args[param_name.to_sym]
      param.simulation_value = user_value unless user_value.nil?
    end

    render action: "simulate"
  end

  def notify
    Notifier.logger.info "Sending Registered Notifications"

    Notifier.logger.info "[Notifications] #{Time.now.to_fs} - Notifications from DB"
    notifications = []
    notifications_attachments = {}

    # Get the next execution time arel table
    next_execution = Notification.arel_table[:next_execution]

    # Find notifications that should run
    Notification.where.not(frequency: Notification::MANUAL)
      .where(next_execution.lt(Time.now)).each do |notification|
        result = prepare_attachments(notification.execute)
        notifications.concat(result[:notifications])
        notifications_attachments.merge!(result[:notifications_attachments])
      end

    Notifier.send_emails({
      notifications: notifications,
      notifications_attachments: notifications_attachments
    })

    render inline: "Ok", content_type: "text/html"
  end

  private
    def get_query_params
      return params[:query_params].to_unsafe_h if params[:query_params].is_a?(
        ActionController::Parameters
      )
      params[:query_params] || {}
    end

    def prepare_attachments(notification_result)
      notification_result[:notifications].each do |message|
        attachments = notification_result[:notifications_attachments][message]
        next if attachments.blank?
        if attachments[:grades_report_pdf]
          enrollment = Enrollment.find(message[:enrollments_id])
          filename = "grades_report.pdf"
          signature_type = 0
          attachments[:grades_report_pdf][:file_contents] =
            render_enrollments_grades_report_pdf(enrollment, filename, signature_type, watermark: true)
        end
      end
      notification_result
    end
end

app/helpers/notifications_helper.rb
# Copyright (c) Universidade Federal Fluminense (UFF).
# This file is part of SAPOS. Please, consult the license terms in the LICENSE file.

# frozen_string_literal: true

module NotificationsHelper
  def query_sql_form_column(record, options)
    code_mirror_view_widget(
      "sql_query-view-#{record.id}", "text/x-mysql",
      (record.query.try(:sql) || ""), true
    )
  end

  def body_template_form_column(record, options)
    code_mirror_text_area_widget(
      :body_template, "record_body_template_#{record.id}", "liquid",
      options.merge(
        value: record.body_template ||
        I18n.t("active_scaffold.notification.body_template_default_liquid")
      ),
      set_size=35,
      line_wrapping=true
    )
  end

  def next_execution_column(record, options)
    return "-" if record.blank?
    return "-" if record.next_execution.nil?
    return "-" if record.frequency == Notification::MANUAL
    I18n.localize(record.next_execution, format: :day)
  end

  def sql_query_show_column(record, column)
    code_mirror_view_widget(
      "sql_query-view-#{record.id}", "text/x-mysql",
      (record.query.try(:sql) || "")
    )
  end

  def body_template_show_column(record, column)
    code_mirror_view_widget(
      "body_template-view-#{record.id}", "liquid", record.body_template
    )
  end

  def notification_param_query_param_form_column(record, options)
    options[:value] = record.query_param_id
    label(
      :record_value_1_params, record.id,
      ("(#{record.value_type}) ") + record.name
    ) + hidden_field(:record, :query_param, options)
  end
end

app/views/notifications/_body_template_form_column.html.erb
<% column_options = active_scaffold_input_options(column, scope, object: record) %>
<dl>
  <dt>
    <%= label_tag label_for(column, column_options), column.label %>
    <br>
    <span class="description">
      <span class="desc-title">Os campos de template utilizam linguagem Liquid. <a href="https://shopify.dev/docs/api/liquid/"> Ver detalhes </a>.</span>
      <span class="desc-title">Variáveis: </span>
      <ul>
        <li>
          <strong>{{ coluna }}</strong> <br>
          Escreve uma coluna da consulta no corpo do texto da declaração
        </li>
        <li>
          <strong>{{ records }}</strong> <br>
          Lista com todos os resultados
<pre>{% for record in records %}
  {{ record.coluna }};
{% endfor %}</pre>
        </li>
      </ul>
      <span class="desc-title">Filtros: </span>
      <ul>
        <li>
          <strong>{{ data | localize: 'short' }}</strong> <br>
          Imprime tempo com formato diferente. Opções de formato: <br>
          <span title="%A, %d de %B de %Y, %H:%M h">'default'</span>,
          <span title="%d-%m-%Y">'defaultdate'</span>,
          <span title="%H:%M h">'short'</span>,
          <span title="%d de %B">'shortdate'</span>,
          <span title="%A, %d de %B de %Y, %H:%M h">'long'</span>,
          <span title="%d de %B de %Y">'longdate'</span>,
          <span title="%a, %d %b %Y %H:%M:%S">'picker'</span>,
          <span title="%A, %d de %B de %Y">'day'</span>,
          <span title="%B-%Y">'monthyear'</span>,
          <span title="%B/%Y">'monthyear2'</span>
        </li>
      </ul>
      <span class="desc-title">Tags: </span>
      <ul>
        <li>
          <strong>language en</strong> <br>
          Ao utilizar esta tag, a formatação de datas pelo localize dentro dela fica em inglês.
<pre>{% language en %}
  {{ data | localize: 'long' }}
{% endlanguage %}</pre>
        </li>
        <li>
          <strong>emails <i>Papel</i></strong> <br>
          Retorna todos emails de um determinado papel.
<pre>{% emails Secretaria %}
{% emails Coordenação %}</pre>
        </li>
      </ul>
    </span>
  </dt>
  <dd>
    <%= body_template_form_column record, column_options %>
  </dd>
</dl>

app/views/notifications/_params_form.html.erb
<% resource_name = resource.class.to_s.downcase %>
<h5>Parâmetros de consulta</h5>
<div>
  <table class="showtable listed-records-table">
    <thead>
    <tr>
      <th>Tipo</th>
      <th>Variável</th>
      <th>Valor</th>
      <th>Default</th>
    </tr>
    </thead>
    <tbody class="records">
    <% query_params.each do |param| %>
      <tr class="record">
        <td>
          <%= param.value_type %>
        </td>
        <td>
          <%= param.name %>
        </td>
        <% if Notification::DERIVED_PARAMS.include?(param.name) %>
          <td>
            <span><%= param.value %></span>
          </td>
          <td>
            (derivado de <b><%= Notification::DERIVED_PARAMS[param.name] %></b>)
          </td>
        <% else %>
          <td>
            <% if param.type.list? || param.default_value.nil? %>
              <%= text_field_tag(
                "#{resource_name}_#{resource.id}_#{param.name}",
                param.value,
                data: {
                  name: "query_params[#{param.name}]",
                    "link-target" => "#as_#{resource_name.pluralize}-simulate-#{resource.id}-link"
                },
                id: "#{resource_name}_#{resource.id}_#{param.name}",
                class: "_onchange_param_field _param_field _param_type_#{param.value_type.downcase}"
              ) %>
            <% else %>
              <%= text_field_tag(
                "#{resource_name}_#{resource.id}_#{param.name}",
                param.parsed_value,
                data: {
                  name: "query_params[#{param.name}]",
                    "link-target" => "#as_#{resource_name.pluralize}-simulate-#{resource.id}-link"
                },
                id: "#{resource_name}_#{resource.id}_#{param.name}",
                class: "_onchange_param_field _param_field _param_type_#{param.value_type.downcase}"
              ) %>
            <% end %>
          </td>
          <td>
            Defaults:
            <small class="_default_value" data-default_value="<%= param.default_value %>">
              <a href="javascript:void(o)">(Consulta: <%= param.default_value %>)</a>
            </small>
            <small class="_default_value" data-default_value="<%= param.simulation_value %>">
              <a href="javascript:void(o)">(Notificação: <%= param.simulation_value %>)</a>
            </small>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>

  <script type="text/javascript">

      $("._default_value").click(function () {
          var _this = $(this);
          _this.parents("tr").first().find("._param_field").val(_this.data("default_value")).trigger("change");
      });

      $("._onchange_param_field").change(function () {
          var link = $($(this).data("link-target"));
          var p = link.prop("search").replace(/^\?/, "");
          var params = queryStringToHash(p);
          var params_elements = $("._onchange_param_field");
          for (var i = 0, len = params_elements.length; i < len; i++) {
              var current_param = $(params_elements[i]);
              params[current_param.data("name")] = current_param.val()
          }
          link.prop("search", $.param(params));
      }).first().trigger("change");

      $("._param_type_date").datepicker();

  </script>
</div>

app/views/notifications/_query_form_column.html.erb
<%
  column_options = active_scaffold_input_options(column, scope, object: record)
  attributes = field_attributes(column, record)
  attributes[:class] = "#{attributes[:class]} #{col_class}" if col_class.present?
  field = unless only_value
    active_scaffold_input_for column, scope, column_options
  else
    content_tag(
      :span, get_column_value(record, column),
      column_options.except(:name, :object)
    ) << hidden_field(
      :record,
      column.association ? column.association.foreign_key : column.name,
      column_options
    )
  end
%>
<%= content_tag :dl, attributes do %>
  <dt>
    <%= label_tag label_for(column, column_options), column.label %>
    <div>
      <span class="description"><%= record.query.try :description %></span>
    </div>
  </dt>
  <dd>
    <%= field %>
    <%= link_to(
      "SQL", "javascript:void(0)",
      onclick: "$('##{column_options[:id] + "container"}').toggle();".html_safe
    ) %>
    <%= loading_indicator_tag(
      action: :render_field, id: params[:id]
    ) if column.update_columns %>
    <%= content_tag(
      :span, column.description, class: "description"
    ) if column.description.present? %>
    <div id="<%= column_options[:id] + "container" %>">
      <%= query_sql_form_column(record, column_options) %>
    </div>
  </dd>
<% end %>

app/views/notifications/_sql_query_form_column.html.erb
<% column_options = active_scaffold_input_options(column, scope, object: record) %>
<dl>
  <dt>
    <%= label_tag label_for(column, column_options), column.label %>
    <br/>
    <span class="description">
      <span class="desc-title">Variáveis: </span>
      <ul>
        <li><strong>%{data_consulta}</strong> <br/> Data de consulta. <br/> Ex: <strong>15/01/2014</strong>, para frequencia anual e offset de consulta 14d</li>
        <li><strong>%{ano_semestre_atual}</strong> <br/> Ano do semestre da data de consulta. Ex: <strong>2013</strong>, para data de consulta 15/01/2014</li>
        <li><strong>%{numero_semestre_atual}</strong> <br/> Número do semestre da data de consulta. Ex: <strong>2</strong>, para data de consulta 15/01/2014</li>
        <li><strong>%{ano_ultimo_semestre}</strong> <br/> Ano do semestre anterior à data de consulta. Ex: <strong>2013</strong>, para data de consulta 15/01/2014</li>
        <li><strong>%{numero_ultimo_semestre}</strong> <br/> Número do semestre anterior à data de consulta. Ex: <strong>1</strong>, para data de consulta 15/01/2014</li>
      </ul>
    </span>
  </dt>
  <dd>
    <%= sql_query_form_column record, column_options %>
  </dd>
</dl>

app/views/notifications/simulate.html.erb
<h4> <%= @notification.to_label %> </h4>

<%= render "notifications/params_form", resource: @notification, query_params: @query_params %>

<div class="actions" style="display: block; margin: 10px 0 0 0;">
  <a id="as_notifications-simulate-<%= @notification.id %>-link"
     class="simulate as_action again"
     href="javascript:void(0)">
    <i class="fa fa-table" title="Simular"></i>Simular
  </a>
  &nbsp;&nbsp;
  <%= render "queries/show_sql", sql_query: @query_sql %>
</div>

<% if @messages.size.zero? && params[:query_params].try(:[], :data_consulta).nil? %>
  <div style="margin: 10px 0">Faça uma simulação</div>

<% elsif @messages.size.zero? && params[:query_params].try(:[], :data_consulta) %>
  <div style="margin: 10px 0">Esta consulta não retornou nenhum resultado</div>
<% else %>
  <div class="actions" style="display: block">
    <p class="simulate_query_date">
      <span>
      <% if params[:query_params].try(:[], :data_consulta) %>
        <%= I18n.t("active_scaffold.notification.query_date") %>:
        <%= params[:query_params][:data_consulta] %>
      <% end %>
      </span>
      &nbsp;&nbsp;&nbsp;
      <a id="as_notifications-execute_now-<%= @notification.id %>-link"
          data-remote="true" data-method="post" class="execute_now as_action"
          href="<%= execute_now_notification_path(
            @notification,
            query_params: params[:query_params]
          ) %>">
        <i class="fa fa-mail-forward" title="Notificar agora"></i>Notificar agora
      </a>
      <%= loading_indicator_tag(action: :execute_now, id: @notification.id) %>
    </p>
  </div>

  <table class="notification-results showtable listed-records-table">
    <thead>
    <tr>
      <th><%= I18n.t("activerecord.attributes.notification_log.to") %></th>
      <th><%= I18n.t("activerecord.attributes.notification_log.subject") %></th>
      <th><%= I18n.t("activerecord.attributes.notification_log.body") %></th>
    </tr>
    </thead>
    <tbody class="records">
    <% @messages.each_with_index do |message, index| %>
        <% tr_class = index.odd? ? "even-record" : "" %>
        <tr class="record <%= tr_class %>">
          <td><%= message[:to] %></td>
          <td><%= message[:subject] %></td>
          <td><%= message[:body].html_safe %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<p class="form-footer">
  <%= link_to(
    as_(:close), main_path_to_return,
    class: "as_cancel", remote: request.xhr?
  ) %>
  <%= loading_indicator_tag(action: :create, id: params[:id]) %>
</p>

<script type="text/javascript">
  $(function () {
    $(".simulate.as_action.again").click(function () {
      ActiveScaffold.find_action_link(
        $("#as_notifications-simulate-<%= @notification.id %>-link")
      ).reload();
    });
  });
</script>