config/routes.rb
# Copyright (c) Universidade Federal Fluminense (UFF).
# This file is part of SAPOS. Please, consult the license terms in the LICENSE file.

# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  concern :active_scaffold, ActiveScaffold::Routing::Basic.new(association: true)
  concern :active_scaffold_association, ActiveScaffold::Routing::Association.new

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "application#root"

  resources :enrollment_holds do concerns :active_scaffold end

  resources :scholarship_suspensions do concerns :active_scaffold end

  devise_for :users,  controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    unlocks: "users/unlocks",
    invitations: "users/user_invitations",
  }, skip: [:registrations]

  devise_scope :user do
    get "users/sign_up",
      to: "users/registrations#new", as: :new_user_registration
    get "users/profile",
      to: "users/registrations#edit", as: :edit_user_registration
    patch "users/profile",
      to: "users/registrations#update", as: :user_registration
    put "users/profile", to: "users/registrations#update"
    post "users/profile", to: "users/registrations#update"
    post "change_role", to: "user_roles#change_role", as: :change_role
    delete "users/profile", to: "users/registrations#update"
  end


  resources :versions do
    concerns :active_scaffold
  end

  resources :professor_research_areas do
    concerns :active_scaffold
    record_select_routes
  end

  resources :class_enrollments do
    concerns :active_scaffold
    record_select_routes
  end

  resources :allocations do
    concerns :active_scaffold
  end

  resources :course_classes do
    concerns :active_scaffold
    record_select_routes
    member do
      get "summary_pdf"
      get "summary_xls"
    end
    collection do
      get "class_schedule_pdf"
    end
  end

  resources :class_schedules do
    concerns :active_scaffold
    member do
      get "class_schedule_pdf"
    end
  end

  resources :course_types do
    concerns :active_scaffold
  end

  resources :courses do
    concerns :active_scaffold
    record_select_routes
  end

  resources :research_areas do
    concerns :active_scaffold
    record_select_routes
  end

  resources :research_lines do
    concerns :active_scaffold
    record_select_routes
  end

  resources :professor_research_lines do
    concerns :active_scaffold
    record_select_routes
  end

  resources :course_research_lines do
    concerns :active_scaffold
  end

  get "credits/show"

  resources :phase_durations do
    concerns :active_scaffold
  end

  resources :deferrals do
    concerns :active_scaffold
  end

  resources :deferral_types do
    concerns :active_scaffold
  end

  resources :accomplishments do
    concerns :active_scaffold
  end

  resources :phases do
    concerns :active_scaffold
  end

  resources :cities do
    concerns :active_scaffold
    get "autocomplete", on: :collection
  end

  resources :states do
    concerns :active_scaffold
    get "cities", on: :member
    get "autocomplete", on: :collection
  end

  resources :countries do
    concerns :active_scaffold
    get "states", on: :member
    get "autocomplete", on: :collection
  end

  resources :users do
    concerns :active_scaffold
    record_select_routes
  end

  resources :roles do
    concerns :active_scaffold
  end

  resources :user_roles do
    concerns :active_scaffold
    record_select_routes
  end

  

  resources :scholarship_durations do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
    end
  end

  resources :scholarships do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
    end
  end

  resources :advisements do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
    end
  end

  resources :affiliation do
    concerns :active_scaffold
    record_select_routes
  end

  resources :professors do
    concerns :active_scaffold
    record_select_routes
  end

  resources :scholarship_types do
    concerns :active_scaffold
  end

  resources :dismissals do
    concerns :active_scaffold
  end

  resources :dismissal_reasons do
    concerns :active_scaffold
  end

  resources :enrollments do
    concerns :active_scaffold
    record_select_routes
    collection do
      get "to_pdf"
      get "new_users"
      post "create_users"
    end
    member do
      get "academic_transcript_pdf"
      get "academic_transcript/:signature_type.pdf", to: "enrollments#override_signature_transcript_pdf", as: :override_signature_transcript_pdf
      get "grades_report_pdf"
      get "grades_report/:signature_type.pdf", to: "enrollments#override_signature_grades_report_pdf", as: :override_signature_grades_report_pdf
    end
  end

  resources :enrollment_statuses do
    concerns :active_scaffold
  end

  resources :students do
    concerns :active_scaffold
    record_select_routes
  end

  resources :majors do
    concerns :active_scaffold
    record_select_routes
  end

  resources :assertions do
    concerns :active_scaffold
  end

  resources :levels do
    concerns :active_scaffold
  end

  resources :institutions do
    concerns :active_scaffold
    record_select_routes
  end

  resources :sponsors do
    concerns :active_scaffold
  end

  resources :advisement_authorizations do
    concerns :active_scaffold
  end

  resources :student_majors do
    concerns :active_scaffold
    record_select_routes
  end

  resources :custom_variables do
    concerns :active_scaffold
  end

  resources :program_levels do
    concerns :active_scaffold
  end

  resources :thesis_defense_committee_participations do
    concerns :active_scaffold
    record_select_routes
  end

  resources :notification_logs do
    concerns :active_scaffold
  end

  resources :notifications do
    concerns :active_scaffold
    member do
      post "execute_now"
      get "simulate"
    end

    collection do
      get "notify"
    end
  end

  resources :queries do
    concerns :active_scaffold
    member do
      get "execute"
    end
  end

  resources :query_params do
    concerns :active_scaffold
  end

  resources :report_configurations do
    concerns :active_scaffold
    collection do
      put "preview"
      post "preview"
      patch "preview"
    end
    member do
      get "logo"
    end
  end


  resources :course_research_areas do
    concerns :active_scaffold
  end

  scope module: "admissions" do
    resources :admission_processes do
      concerns :active_scaffold
      member do
        get :short_pdf
        get :complete_pdf
        get :complete_xls

        get :phase_status
        post :consolidate_phase
        get :rankings
        post :calculate_ranking
      end
      collection do
        get :custom_report
        match :reset_report, via: [:get, :post]
        post :custom_report_generate
      end
      record_select_routes
    end

    resources :admission_applications do
      concerns :active_scaffold
      collection do
        get :configure_all
      end
      member do
        get :configuration
        put :undo_consolidation
        put :cancel
        get :map_student
        post :map_student_form
        post :map_student_form_create_update
      end
      record_select_routes
    end

    resources :form_templates do
      concerns :active_scaffold
      get :populate_field, on: :collection
      member do
        get :populate_field
        get :preview
        post :preview
        patch :preview
      end
      record_select_routes
    end

    resources :consolidation_templates do
      concerns :active_scaffold
    end

    resources :form_fields do
      concerns :active_scaffold
    end

    resources :consolidation_form_fields do
      concerns :active_scaffold
    end

    resources :filled_forms do
      concerns :active_scaffold
    end

    resources :filled_form_fields do
      concerns :active_scaffold
    end

    resources :filled_form_field_scholarities do
      concerns :active_scaffold
    end

    resources :letter_requests do
      concerns :active_scaffold
    end

    resources :admissions, only: [:index, :show] do
      post :find, on: :collection
      post :create, on: :member
      resources :apply, only: [:show, :new, :create, :edit, :update] do
        post :update, on: :member
      end
      resources :letters, only: [:show, :update]
    end

    resources :form_autocompletes, only: [] do
      get :city, on: :collection
      get :state, on: :collection
      get :country, on: :collection
      get :institution, on: :collection
      get :course, on: :collection
      get :form_field, on: :collection
    end

    resources :form_conditions do
      concerns :active_scaffold
    end

    resources :admission_committees do
      concerns :active_scaffold
      get :populate_authorized, on: :collection
      get :populate_professors, on: :collection
      get :populate_coordination, on: :collection
      get :populate_secretary, on: :collection
      member do
        get :populate_authorized
        get :populate_professors
        get :populate_coordination
        get :populate_secretary
      end
      record_select_routes
    end

    resources :admission_committee_members do
      concerns :active_scaffold
    end

    resources :admission_phases do
      concerns :active_scaffold
      record_select_routes
    end

    resources :admission_phase_committees do
      concerns :active_scaffold
    end

    resources :admission_process_phases do
      concerns :active_scaffold
    end

    resources :admission_phase_results do
      concerns :active_scaffold
    end

    resources :admission_phase_evaluations do
      concerns :active_scaffold
    end

    resources :admission_pendencies do

app/views/enrollments/_new_users.html.erb
<%= render partial: "base_form", locals: {
  form_action: :create_users,
  body_partial: "new_users_form",
  headline: t("active_scaffold.new_users_headline"),
  submit_text: t("active_scaffold.new_users_submit")
} %>

app/views/enrollments/_new_users_form.html.erb
<ol class="customform form">
  <li class="form-element">
    <%=readonly_dl_input("Matrículas", @counts, :enrollments)%>
  </li>
  <li class="form-element">
    <%=readonly_dl_input("... que permitem usuários <span id='enrollment-info'>[?]</span>
    <div id='toggle-enrollment-info'> #{'Tipo'.pluralize(@statuses_with_users.count)}: #{@statuses_with_users.to_sentence(locale: :'pt-BR')}
    <br> Se quiser incluir outros tipos, configure \"Tipos de Matrícula\" </div>", @counts, :allowedenrollments)%>
  </li>
  <li class="form-element">
    <%=readonly_dl_input("Alunos", @counts, :students)%>
  </li>
  <li class="form-element">
    <%=readonly_dl_input("... vinculados a usuários", @counts, :existingstudents)%>
  </li>
  <li class="form-element">
    <%=readonly_dl_input("... sem email", @counts, :noemail)%>
  </li>
  <li class="form-element">
    <dl>
      <dt><label>Adicionar</label></dt>
      <dd>
        <label>
          <input type="radio" id="add_default" name="add_option" value="default" checked/>
          <%=pluralize(@counts[:default], 'aluno') %> <%= 'válido'.pluralize(@counts[:default]) %>
        </label>
        <br>
        <label>
          <input type="radio" id="add_dismissed" name="add_option" value="dismissed"/>
          <%=pluralize(@counts[:dismissed], 'aluno') %> <%= 'desligado'.pluralize(@counts[:dismissed]) %>
        </label>
        <br>
        <label>
          <input type="radio" id="add_all" name="add_option" value="all"/>
          <%=pluralize(@counts[:all], 'aluno') %> <%= 'válido'.pluralize(@counts[:all]) %> ou <%= 'desligados'.pluralize(@counts[:all]) %>
        </label>
      </dd>
    </dl>
  </li>
</ol>

<script>

$('#enrollment-info').click(function () {
  $("#toggle-enrollment-info").toggle();
})

</script>

app/views/enrollments/_show_academic_transcript_signature_override_links.html.erb
<div style="display: flex; gap: 20px;">
  <% if can?(:academic_transcript_pdf, @record) %>
    <% if can?(:override_report_signature_type, @record) %>
      <%= link_to 'Sem Assinatura', override_signature_transcript_pdf_enrollment_path(id: @record.id, signature_type: :no_signature) %>
      <%= link_to 'Assinatura Manual', override_signature_transcript_pdf_enrollment_path(id: @record.id, signature_type: :manual) %>
      <%= link_to 'Assinatura por QR Code', override_signature_transcript_pdf_enrollment_path(id: @record.id, signature_type: :qr_code) %>
    <% else %>
      <%= link_to 'Gerar', academic_transcript_pdf_enrollment_path(id: @record.id, format: :pdf) %>
    <% end %>
  <% else %>
   -
  <% end %>
</div>

app/views/enrollments/_show_advisements_table.html.erb
<table class="showtable listed-records-table">
  <thead>
    <tr>
      <th><%= I18n.t("activerecord.attributes.advisement.professor") %></th>
      <% if show_enrollment_number %>
        <th><%= I18n.t("activerecord.attributes.advisement.professor_enrollment_number") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="records">
    <% count = 0 %>
    <% advisements.each do |advisement| %>
      <% count += 1 %>
      <% tr_class = count.even? ? "even-record" : "" %>
      <% if advisement.main_advisor %>
        <tr class="record <%= tr_class %>">
          <td title='<%= I18n.t("activerecord.attributes.advisement.main_advisor") %>'>
            <strong><%= advisement.professor.name %>*</strong>
          </td>
          <% if show_enrollment_number %>
            <td><strong><%= advisement.professor.enrollment_number %></strong></td>
          <% end %>
        </tr>
      <% else %>
        <tr class="record <%= tr_class %>">
          <td><%= advisement.professor.name %></td>
          <% if show_enrollment_number %>
            <td><%= advisement.professor.enrollment_number %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/enrollments/_show_class_enrollments_table.html.erb
<% no_gpr_class_enrollments = [] %>

<table class="showtable listed-records-table">
  <thead>
    <tr>
      <th><%= I18n.t("activerecord.attributes.course_class.semester") %></th>
      <th><%= I18n.t("activerecord.models.course.one") %></th>
      <th><%= I18n.t("activerecord.attributes.class_enrollment.situation") %></th>
      <th><%= I18n.t("activerecord.attributes.class_enrollment.grade") %></th>
      <th><%= I18n.t("activerecord.attributes.class_enrollment.disapproved_by_absence") %></th>
      <% if show_obs %>
        <th><%= I18n.t("activerecord.attributes.class_enrollment.obs") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="records">
    <% count = 0 %>
    <% class_enrollments.each do |class_enrollment| %>
      <% count += 1 %>
      <% tr_class = count.even? ? "even-record" : "" %>
      <% no_gpr_class_enrollments << class_enrollment if class_enrollment.grade_not_count_in_gpr.present? %>
      <tr class="record <%= tr_class %>">
        <td><%= class_enrollment.course_class.semester_label %></td>
        <td><%= class_enrollment.course_class.course.name %></td>
        <td><%= class_enrollment.situation %></td>
        <td><%= class_enrollment.grade_label(false) %></td>
        <% if class_enrollment.attendance_to_label == "I" %>
          <td>Sim</td>
        <% else %>
          <td>Não</td>
        <% end %>
        <% if show_obs %>
          <td><%= class_enrollment.obs %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if no_gpr_class_enrollments.any? %>
  <div class="grade-not-count-in-gpr-justification-label"> * Disciplinas que não contabilizam nota: </div>
  <table class="showtable listed-records-table">
    <thead>
      <tr>
        <th><%= I18n.t("activerecord.attributes.course_class.semester") %></th>
        <th><%= I18n.t("activerecord.models.course.one") %></th>
        <th><%= I18n.t("activerecord.attributes.class_enrollment.justification_grade_not_count_in_gpr") %></th>
      </tr>
    </thead>
    <tbody class="records">
      <% count = 0 %>
      <% no_gpr_class_enrollments.each do |class_enrollment| %>
        <% count += 1 %>
        <% tr_class = count.even? ? "even-record" : "" %>
        <tr class="record <%= tr_class %>">
          <td><%= class_enrollment.course_class.semester_label %></td>
          <td><%= class_enrollment.course_class.course.name %></td>
          <td><%= class_enrollment.justification_grade_not_count_in_gpr %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/enrollments/_show_defense_committee_table.html.erb
<table class="showtable listed-records-table">
  <thead>
    <tr>
      <th><%= I18n.t("activerecord.attributes.professor.name") %></th>
      <th><%= I18n.t("activerecord.attributes.professor.institution.one") %></th>
    </tr>
  </thead>
  <tbody class="records">
    <% count = 0 %>
    <% thesis_defense_committee_professors.each do |professor| %>
      <% count += 1 %>
      <% tr_class = count.even? ? "even-record" : "" %>
      <% date =  thesis_defense_date || dismissal_date %>
      <% affiliation = Affiliation.professor_date(professor, date&.to_date)&.last || Affiliation.of_professor(professor)&.last %>
      <tr class="record <%= tr_class %>">
        <td><%= professor.name %></td>
        <td><%= rescue_blank_text(affiliation&.institution, method_call: :name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/enrollments/_show_deferrals_table.html.erb
<table class="showtable listed-records-table">
  <thead>
    <tr>
      <th><%= I18n.t("activerecord.attributes.deferral.approval_date") %></th>
      <th><%= I18n.t("activerecord.attributes.deferral.deferral_type") %></th>
      <% if show_obs %>
        <th><%= I18n.t("activerecord.attributes.deferral.obs") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="records">
    <% count = 0 %>
    <% deferrals.each do |deferral| %>
      <% count += 1 %>
      <% tr_class = count.even? ? "even-record" : "" %>
      <tr class="record <%= tr_class %>">
        <td><%= I18n.localize(deferral.approval_date, format: dateformat) %></td>
        <td><%= deferral.deferral_type.name %></td>
        <% if show_obs %>
          <td><%= deferral.obs %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/enrollments/_show_documents_table.html.erb
<table class="showtable listed-records-table">
  <thead>
  <tr>
    <th><%= t "activerecord.models.assertion.one" %></th>
    <% if can? :override_report_signature_type, Enrollment %>
      <th>Sem ass.</th>
      <th>Ass. manual</th>
      <th>Ass. QR Code</th>
    <% else %>
      <th>Ação</th>
    <% end %>
  </tr>
  </thead>
  <tbody class="records">
  <% count = 0 %>
  <tr class="record">
    <td><%= t("pdf_content.enrollment.grades_report.link") %></td>
    <% if can? :override_report_signature_type, Enrollment %>
      <td><%= link_to 'Gerar', override_signature_grades_report_pdf_enrollment_path(id: enrollment.id, signature_type: :no_signature, format: :pdf), target: "_blank", method: :get %></td>
      <td><%= link_to 'Gerar', override_signature_grades_report_pdf_enrollment_path(id: enrollment.id, signature_type: :manual, format: :pdf), target: "_blank", method: :get %></td>
      <td><%= link_to 'Gerar', override_signature_grades_report_pdf_enrollment_path(id: enrollment.id, signature_type: :qr_code, format: :pdf), target: "_blank", method: :get %></td>
    <% else %>
      <td><%= link_to "Gerar", grades_report_pdf_enrollment_path(id: enrollment.id, format: :pdf), target: "_blank", method: :get %></td>
    <% end %>
  </tr>
  <% if can?(:academic_transcript_pdf, enrollment) %>
    <tr class="record">
      <td><%= t("pdf_content.enrollment.academic_transcript.link") %></td>
      <% if can? :override_report_signature_type, Enrollment %>
        <td><%= link_to 'Gerar', override_signature_transcript_pdf_enrollment_path(id: enrollment.id, signature_type: :no_signature, format: :pdf), target: "_blank", method: :get %></td>
        <td><%= link_to 'Gerar', override_signature_transcript_pdf_enrollment_path(id: enrollment.id, signature_type: :manual, format: :pdf), target: "_blank", method: :get %></td>
        <td><%= link_to 'Gerar', override_signature_transcript_pdf_enrollment_path(id: enrollment.id, signature_type: :qr_code, format: :pdf), target: "_blank", method: :get %></td>
      <% else %>
        <td><%= link_to "Gerar", academic_transcript_pdf_enrollment_path(id: enrollment.id, format: :pdf), target: "_blank", method: :get %></td>
      <% end %>
    </tr>
  <% end %>
  <% allowed_assertions.each do |assertion| %>
    <% count += 1 %>
    <% tr_class = count.even? ? "even-record" : "" %>
    <tr class="record <%= tr_class %>">
      <td><%= assertion.name %></td>
      <% if can? :override_report_signature_type, Enrollment %>
        <td><%= link_to "Gerar", override_signature_assertion_pdf_assertion_path(id: assertion.id, query_params: {matricula_aluno: enrollment.enrollment_number}, signature_type: :no_signature, format: :pdf), target: "_blank", method: :get %></td>
        <td><%= link_to "Gerar", override_signature_assertion_pdf_assertion_path(id: assertion.id, query_params: {matricula_aluno: enrollment.enrollment_number}, signature_type: :manual, format: :pdf), target: "_blank", method: :get %></td>
        <td><%= link_to "Gerar", override_signature_assertion_pdf_assertion_path(id: assertion.id, query_params: {matricula_aluno: enrollment.enrollment_number}, signature_type: :qr_code, format: :pdf), target: "_blank", method: :get %></td>
      <% else %>
        <td><%= link_to "Gerar", assertion_pdf_assertion_path(id: assertion.id, query_params: {matricula_aluno: enrollment.enrollment_number}, format: :pdf), target: "_blank", method: :get %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/enrollments/_show_grades_report_signature_override_links.html.erb
<div style="display: flex; gap: 20px;">
  <% if can?(:override_report_signature_type, @record) %>
      <%= link_to 'Sem Assinatura', override_signature_grades_report_pdf_enrollment_path(id: @record.id, signature_type: :no_signature, transcript: true) %>
      <%= link_to 'Assinatura Manual', override_signature_grades_report_pdf_enrollment_path(id: @record.id, signature_type: :manual, transcript: true) %>
      <%= link_to 'Assinatura por QR Code', override_signature_grades_report_pdf_enrollment_path(id: @record.id, signature_type: :qr_code, transcript: true) %>
  <% else %>
    <%= link_to 'Gerar', grades_report_pdf_enrollment_path(id: @record.id, format: :pdf) %>
  <% end %>
</div>

app/views/enrollments/_show_holds_table.html.erb
<table class="showtable listed-records-table">
  <thead>
    <tr>
      <th><%= I18n.t("activerecord.attributes.enrollment_hold.semester") %></th>
      <th><%= I18n.t("activerecord.attributes.enrollment_hold.number_of_semesters") %></th>
    </tr>
  </thead>
  <tbody class="records">
    <% count = 0 %>
    <% holds.each do |hold| %>
      <% count += 1 %>
      <% tr_class = count.even? ? "even-record" : "" %>
      <tr class="record <%= tr_class %>">
        <td><%= hold.date_label %></td>
        <td><%= hold.number_label %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/enrollments/_show_phases_table.html.erb
<table class="showtable listed-records-table">
  <thead>
    <tr>
      <th><%= t "activerecord.models.phase.one" %></th>
      <th><%= t "activerecord.attributes.phase_completion.due_date" %></th>
      <th><%= t "activerecord.attributes.phase_completion.completion_date" %></th>
      <% if show_obs %>
        <th><%= t "activerecord.attributes.accomplishment.obs" %></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="records">
    <% count = 0 %>
    <% phase_completions.each do |phase_completion| %>
      <% count += 1 %>
      <% tr_class = count.even? ? "even-record" : "" %>
      <% completion_date = phase_completion.completion_date.nil? ?
        "-" : I18n.l(phase_completion.completion_date, format: dateformat)
      %>
      <% accomplishment = phase_completion.phase_accomplishment %>
      <tr class="record <%= tr_class %>">
        <td><%= phase_completion.phase.name %></td>
        <td><%= I18n.l(phase_completion.due_date, format: dateformat) %></td>
        <td><%= completion_date %></td>
        <% if show_obs %>
          <td><%= accomplishment.nil? ? "-" : accomplishment.obs %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/enrollments/_show_scholarships_table.html.erb
<table class="showtable listed-records-table">
  <thead>
    <tr>
      <th><%= I18n.t("activerecord.attributes.scholarship.scholarship_number") %></th>
      <% if show_sponsor %>
        <th><%= I18n.t("activerecord.attributes.scholarship.sponsor") %></th>
      <% end %>
      <th><%= I18n.t("activerecord.attributes.scholarship_duration.start_date") %></th>
      <th><%= I18n.t("activerecord.attributes.scholarship_duration.end_date") %></th>
      <th><%= I18n.t("activerecord.attributes.scholarship_duration.cancel_date") %></th>
      <% if show_obs %>
        <th><%= I18n.t("activerecord.attributes.scholarship_duration.obs") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="records">
    <% count = 0 %>
    <% scholarship_durations.each do |sd| %>
      <% count += 1 %>
      <% tr_class = count.even? ? "even-record" : "" %>
      <% end_date = sd.end_date.nil? ?
        "-" : I18n.localize(sd.end_date, format: dateformat)
      %>
      <% cancel_date = sd.cancel_date.nil? ?
        "-" : I18n.localize(sd.cancel_date, format: dateformat)
      %>
      <tr class="record <%= tr_class %>">
        <td title='<%= sd.scholarship.sponsor.name %>'>
          <%= sd.scholarship.scholarship_number %>
        </td>
        <% if show_sponsor %>
          <td> <%= sd.scholarship.sponsor.name %> </td>
        <% end %>
        <td><%= I18n.localize(sd.start_date, format: dateformat) %></td>
        <td><%= end_date %></td>
        <td><%= cancel_date %></td>
        <% if show_obs %>
          <td><%= sd.obs %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/enrollments/new_users.html.erb
<div class="active-scaffold">
  <div class="create-students-view <%= "#{id_from_controller params[:controller]}-view" %> view">
    <%= render partial: "new_users" -%>
  </div>
</div>

app/views/enrollments/on_create_users.js.erb
try {
<%
  form_selector ||= "#{element_form_id(action: :create_users)}"
%>
var action_link = ActiveScaffold.find_action_link('<%= form_selector %>');
if (action_link) action_link.close(true);
<%= render partial: "refresh_list", no_history: true %>
} catch (e) { alert('RJS error:\n\n' + e.toString());}